name: Test

on:
  push:
    branches: [master, main, devel]
  pull_request:
    branches: [master, main, devel]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Install mrun
        run: uv tool install -e .

      - name: Install pytest
        run: pip install pytest

      - name: Check version
        run: mrun --version

      - name: Run tests
        run: pytest -v